name: autoupdate
on:
  push: {}
  schedule:
    - cron: "*/5 * * * *"
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://anarast/autoupdate-test
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
